shoulder_pan_joint: 0.0
shoulder_lift_joint: -2.39
elbow_joint: 2.4
wrist_1_joint: -3.15
wrist_2_joint: -1.58
wrist_3_joint: 3.15
<<<<<<< HEAD

=======
>>>>>>> 2695dfae5ecd443985e099eccf956c16477e619c

